org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official

# Banderas críticas para Team TX y motor OsmAnd
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.newDsl=false
android.nonTransitiveRClass=false

# Rendimiento del build
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.workers.max=4
kotlin.compiler.execution.strategy=in-process
org.gradle.tooling.parallel=true

# Compatibilidad
android.useLatestJlink=false
googleServices.missing.passthrough=true
