apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'de.undercouch.download'

apply from: rootProject.file("versions.gradle")
apply from: 'build-common.gradle'

android {
    compileSdk osmand_compileSdk
    buildToolsVersion = osmand_buildToolsVersion

    namespace "net.osmand.plus"

    defaultConfig {
        minSdk osmand_minSdk
        targetSdk osmand_targetSdk
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        resValue "string", "app_name", "OsmAnd"
        resValue "string", "app_edition", ""
    }

    buildFeatures {
        aidl true
        compose true
        buildConfig true
        resValues true
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress "qz"
        cruncherEnabled = false
    }

    sourceSets {
        main {
            manifest.srcFile "AndroidManifest.xml"
            jniLibs.srcDirs = ["libs"]
            aidl.srcDirs = ["src"]
            java.srcDirs = ["src", "src-gms", "src-google"]
            kotlin.srcDirs = ["src", "src-gms", "src-google"]
            resources.srcDirs = ["src"]
            res.srcDirs = ["res", layout.buildDirectory.dir("generated/osmand/res")]
            assets.srcDirs = ["assets", layout.buildDirectory.dir("generated/osmand/assets")]
        }
        androidTest {
            java.srcDirs = ["test/java"]
            res.srcDirs = ["test/res"]
            assets.srcDirs = ["test/assets"]
        }
    }

    flavorDimensions "abi"
    productFlavors {
        // ABI
        armv7 {
            dimension "abi"
            ndk {
                abiFilters 'armeabi-v7a'
            }
        }
        arm64 {
            dimension "abi"
            ndk {
                abiFilters 'arm64-v8a'
            }
        }
        armonly {
            dimension "abi"
            ndk {
                abiFilters 'arm64-v8a', 'armeabi-v7a'
            }
        }
        fat {
            dimension "abi"
            ndk {
                abiFilters 'arm64-v8a', 'x86', 'x86_64', 'armeabi-v7a'
            }
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        aidl true
        compose true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
            pickFirsts += [
                'lib/arm64-v8a/libc++_shared.so',
                'lib/armeabi-v7a/libc++_shared.so',
                'lib/x86/libc++_shared.so',
                'lib/x86_64/libc++_shared.so'
            ]
        }
        exclude '/META-INF/CONTRIBUTORS.md'
        exclude '/META-INF/LICENSE.md'
        exclude '/META-INF/NOTICE.md'
    }
}

tasks.withType(JavaCompile).configureEach {
    dependsOn collectExternalResources
}

tasks.named("preBuild") {
    dependsOn("collectExternalResources")
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs

    implementation project(path: ':OsmAnd-java', configuration: 'android')
    implementation project(':OsmAnd-api')
    implementation project(':OsmAnd-shared')

    implementation libs.kotlin.stdlib
    implementation libs.kotlin.reflect
    implementation libs.okio
    implementation libs.androidx.sqlite.framework

    implementation libs.androidx.multidex
    implementation libs.androidx.gridlayout
    implementation libs.androidx.cardview
    implementation libs.androidx.appcompat
    implementation libs.androidx.material
    implementation libs.androidx.browser
    implementation libs.androidx.preference
    implementation libs.androidx.lifecycle.process
    implementation libs.androidx.activity
    implementation platform(libs.androidx.compose.bom)
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    implementation fileTree(include: ['gnu-trove-osmand.jar', 'icu4j-49_1_patched.jar'], dir: 'libs')

    implementation libs.commons.logging
    implementation libs.commons.codec
    implementation libs.commons.compress
    implementation libs.junidecode
    implementation libs.immutables.gson
    implementation libs.jts.core
    implementation libs.openlocationcode
    implementation libs.billing
    implementation libs.picasso
    implementation libs.rhino
    implementation "net.osmand:antpluginlib:3.8.0@aar"
    implementation "net.osmand:OsmAndCore_android:master-snapshot@aar"
    implementation "net.osmand:OsmAndCore_androidNativeRelease:master-snapshot@aar"

    implementation(libs.taptargetview) {
        exclude group: 'com.android.support'
    }

    debugImplementation "net.osmand:MPAndroidChart:custom-snapshot-debug@aar"
    releaseImplementation "net.osmand:MPAndroidChart:custom-snapshot-release@aar"

    implementation(libs.textfieldboxes) {
        exclude group: 'com.android.support'
    }
    implementation libs.scribejava
    implementation libs.colorpicker
    implementation libs.bouncycastle
    implementation libs.play.review

    implementation libs.androidx.car.app
    implementation libs.androidx.car.app.projected

    implementation libs.play.location
    implementation libs.shimmer
}

// Tasks from build-common.gradle are already applied via apply from: 'build-common.gradle'